### ISSUE TITLE
Modularise menu

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#118]

**Comment by djmiley** [comment]
Is this possible without #65 ?

**Comment by jleft** [comment]
> Is this possible without #65 ?

Yes, I think we can modularise the existing menu. For example, we could handle the `click` events in a menu component and provide a more abstract event for them and propagate this to the top level - such as a _series changed_ event.

However, as #65 is in progress, I think it makes sense to do this after #65? :smiley:

**Comment by djmiley** [comment]
I misspoke, you're right. :) I think I meant to say it is conceptually easier for me to do this after #65.

**Comment by jleft** [comment]
> I misspoke, you're right. :) I think I meant to say it is conceptually easier for me to do this after #65.

Cool, no problem, let's do this after #65 is closed.

**Comment by janakerman** [comment]
@djmiley resolved with #125.

**Comment by jleft** [comment]
Continued in #157 #194
