### ISSUE TITLE
Navbar reset button changes default viewDomain to different thing on mobile and desktop

### ISSUE THREAD

**Issue by CBarrett2** [ScottLogic/d3fc-showcase#136]
Also IMO the default is too small on desktop now the navbar has shrunk. I believe this issue is due to the use of the golden ratio to size the rectangle, rather than just using a multiple of the current period (I would say to use a percentage of the loaded data, but it's possible we will add functionality to load variable amounts of data in future)

**Comment by CBarrett2** [comment]
Resolves #144

**Comment by jleft** [comment]
Resolved in #144
