### ISSUE TITLE
Bug - Area and Bollinger Band overlap

### ISSUE THREAD

**Issue by djmiley** [ScottLogic/d3fc-showcase#137]
Difficult to interpet data when Area & Bollinger Band options are selected
![areaboll](https://cloud.githubusercontent.com/assets/13115186/9331859/98693646-45b9-11e5-91a3-80f99d33cf88.jpg)

**Comment by CBarrett2** [comment]
Similar issue with the line and points series

**Comment by CBarrett2** [comment]
Do people think a reasonable solution to this is to remove the area fill component from bollinger bands? That would also solve a problem in #134 and I can't think of another fix myself. We could then maybe re-style the lines to look a bit nicer

**Comment by CBarrett2** [comment]
![image](https://cloud.githubusercontent.com/assets/12998688/9361606/1f41691a-4694-11e5-9332-f29c8c785548.png)
![image](https://cloud.githubusercontent.com/assets/12998688/9361614/255067b6-4694-11e5-8249-ca7a5e5bd1d8.png) Is what it looks like with no area
