### ISSUE TITLE
Manage dependencies with RequireJS or appropriate alternative

### ISSUE THREAD

**Issue by janakerman** [ScottLogic/d3fc-showcase#138]
After speaking with @jleft last week he mentioned that it may be a good idea to use some kind of JS module library (e.g require JS). However, this would only be suggested if there was a need for it.

I've created this issue to build up information so we can assess that need.

* [Index.html] (https://github.com/ScottLogic/d3fc-showcase/blob/develop/src/index.html#L82) is importing all of the scripts individually, and we're managing the ordering and dependancies here manually. This seems to be working fine at the moment.
* In the [Jasmine config](https://github.com/ScottLogic/d3fc-showcase/pull/84/files#diff-35b4a816e0441e6a375cd925af50752cR254) we're adding the test scripts manually. We can't use a pattern matcher like `**/*.js` as we need to handle the script ordering ourselves (@CBarrett2 - feel free to elaborate on this). This doesn't feel maintainable.

**Comment by CBarrett2** [comment]
Afraid I don't really have anything to add to this!

**Comment by jleft** [comment]
Replaced by #329
