### ISSUE TITLE
Use latest git master d3fc?

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/d3fc-showcase#142]
#114. We can't use our fixes/improvements that are accepted in d3fc until a release happens. Should we use the latest git version? https://docs.npmjs.com/files/package.json#github-urls
Other changes to d3fc could break the showcase chart, but d3fc is pretty stable.

**Comment by janakerman** [comment]
I've just remembered that you can specify a commit hash has at the end of the git URL. That should solve the problem of the D3FC updating from underneath us without explicitly changing the `package.json`. 

@djmiley - might be interest in this as he was looking into this when I spoke to him.

**Comment by djmiley** [comment]
I played around a bit with it, it doesn't have a dist file so couldn't reference it.

**Comment by tlsim** [comment]
Looks like we'd have to build d3fc as part of our build.
