### ISSUE TITLE
Add Loading Screen for Bitcoin data loading

### ISSUE THREAD

**Issue by CBarrett2** [ScottLogic/d3fc-showcase#165]
Panning while a historic data callback comes back means that any subsequent movement from the same pan will move the new data according to the previous data's scale. 

To reproduce: change from generated data to live data then quickly start to pan on the generated data and hold the mouse down. When the new data loads, if you move the mouse (while still held down), the domain will shift to something similar to the domain of the previous set of data.

This could be fixed by adding a loading screen/hiding the charts - it depends how we want to deal with it.

**Comment by jleft** [comment]
> This could be fixed by adding a loading screen/hiding the charts - it depends how we want to deal with it.

Sounds like a good idea to me.

**Comment by jleft** [comment]
Resolved in #439
