### ISSUE TITLE
Exclude livereload script from production build

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#169]
The [LiveReload script](https://github.com/ScottLogic/d3fc-showcase/blob/4168fefd82f43fe4ad52e3a41afef54f1d3e2bcb/src/index.html#L76) should be included in the development build and excluded in the production build.

![LiveReload](https://cloud.githubusercontent.com/assets/2017615/9462903/cd991474-4b10-11e5-9f60-c12f02abcc1a.PNG)

**Comment by djmiley** [comment]
See bottom of https://github.com/ScottLogic/d3fc-showcase/blob/develop/src/index.html
