### ISSUE TITLE
Add option to set period to EOD

### ISSUE THREAD

**Issue by PaulScho** [ScottLogic/d3fc-showcase#180]
Get data in blocks of one day.

**Comment by djmiley** [comment]
Use of `sc.util.domain.filterDataInDateRange` should make this possible

**Comment by djmiley** [comment]
Data points for one day periods should display on relevant times (between trading hours), rather than being centered around odd times as they currently are.

**Comment by Afredon** [comment]
generation now done for midnight, and the span generated ends on current day instead of starting at current day
