### ISSUE TITLE
Clicking outside extent on navbar should move the brush

### ISSUE THREAD

**Issue by CBarrett2** [ScottLogic/d3fc-showcase#190]
![image](https://cloud.githubusercontent.com/assets/12998688/9517760/174a2762-4caa-11e5-9053-654c37d69d02.png)

**Comment by jleft** [comment]
Thanks for raising this.

Just FYI, you can use <kbd>Alt</kbd> + <kbd>Print Screen</kbd> to capture the current window, or use the [Snipping Tool](http://windows.microsoft.com/en-gb/windows/use-snipping-tool-capture-screen-shots#1TC=windows-7) to capture a specific portion of the screen - to avoid having a screenshot of both screens. :smiley:

**Comment by djmiley** [comment]
Ask about expected behaviour in next sprint demo?
