### ISSUE TITLE
Errors run in testing process

### ISSUE THREAD

**Issue by CBarrett2** [ScottLogic/d3fc-showcase#191]
TypeError: ... gets thrown during jamsine testing process - it doesn't seem to happen if main.js is removed from the test src files

**Comment by tlsim** [comment]
Possibly related to #138

**Comment by jleft** [comment]
Full message:

```sh
>> TypeError: 'null' is not an object (evaluating 'd3_window(node).getComputedStyle') at
>> ..\..\C:\Dev\d3fc-showcase\node_modules\d3fc\node_modules\d3\d3.js:742
>> ..\..\C:\Dev\d3fc-showcase\src\assets\js\util\calculateDimensions.js:5
>> ..\..\C:\Dev\d3fc-showcase\src\assets\js\main.js:16
>> ..\..\C:\Dev\d3fc-showcase\src\assets\js\main.js:203
```

Looks like calculateDimensions.js can't handle the lack of elements, so it's breaking.

It's not causing the build to fail, so I've marked this as low priority for now.
