### ISSUE TITLE
Latest Price line in front of axis?

### ISSUE THREAD

**Issue by RuthC-C** [ScottLogic/d3fc-showcase#209]
Right now the latest price line annotation and the axis look a little disheveled: 
![image](https://cloud.githubusercontent.com/assets/9120666/9600867/859a419a-5095-11e5-8dd3-bd9085432b17.png)

Do we want to put the latest price line annotation in front of the axis for clarity?

**Comment by djmiley** [comment]
This occurs when the visible data extent shrinks so that differnece between default tickValues shrinks, fro example shrinking from 1.00 to 0.50 difference. This means new tickValues are drawn on top of the close price annotation.

**Comment by jleft** [comment]
Fixed in https://github.com/ScottLogic/d3fc/pull/529
