### ISSUE TITLE
Better error handling and reporting

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#216]
Most errors are logged to the console (or are unhandled), we should have a better mechanism for this.

Also consider handling errors from external APIs - e.g. too many requests - https://github.com/ScottLogic/d3fc-showcase/pull/206#issuecomment-137447930

**Comment by RuthC-C** [comment]
Are you thinking along the lines of exceptions? try/catch etc?

**Comment by jleft** [comment]
See #445 and #446
