### ISSUE TITLE
Technical Design

### ISSUE THREAD

**Issue by PaulScho** [ScottLogic/d3fc-showcase#260]

**Comment by djmiley** [comment]
(d3, fc, sc)
util.domain -> domain
dimensions.layout -> layout
callbackinvalidator -> data.callbackinvalidator
datamodel -> model

**Comment by djmiley** [comment]
Create an object that deals with domain and data referencing in #269

**Comment by jleft** [comment]
Calculating Y extent from indicators: 

> What if we put an extentAccessor property on the option when we initialise in sc.menu.side, i.e; yLowValue, ['lower', 'upper']? And then ask for the extentAccessor on multi.series.

https://github.com/ScottLogic/d3fc-showcase/pull/281/files#r40999610

**Comment by jleft** [comment]
Closing as split into smaller tasks.
