### ISSUE TITLE
Update to d3fc v1.5.0 causes bollinger bands to not display the series underneath

### ISSUE THREAD

**Issue by djmiley** [ScottLogic/d3fc-showcase#292]
In v1.3.0, we can see the series below the bollinger bands.

![boll](https://cloud.githubusercontent.com/assets/13115186/10543270/5d466aae-7415-11e5-9be3-88df6c11adf3.jpg)

**Comment by djmiley** [comment]
Should probably ask Chris or Colin whether they think series should be drawn in front of indicators.

**Comment by jleft** [comment]
Already fixed in d3fc (not released yet though): https://github.com/ScottLogic/d3fc/commit/30fb8c4dd294c6dcf2853b57949a1df5a8683ef2

**Comment by jleft** [comment]
Fixed in d3fc 2.0.0 and above.
