### ISSUE TITLE
Period selector displays '1 Hour' for every selection

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/d3fc-showcase#308]
Regression at c56caaa
Changing period using period selector successfully sets the chart's period, but the selector itself always displays '1 Hour'. Expected the selector to show the updated period when '5 minutes' or '1 minute' is selected.

**Comment by Afredon** [comment]
I can take a look once I'm done with my rebase if you want

**Comment by djmiley** [comment]
It's because it never worked in the first place, I think, and `selectedIndex` would always be -1. Before `sc.event.dataPeriodChange` does not cause the head menu to rerender, whereas now it does. I solved it by keying on the option's valueString.

**Comment by djmiley** [comment]
See https://github.com/djmiley/d3fc-showcase/blob/3a88ef66e0b3d48e01c12c8f03982078f7b235b3/src/assets/js/menu/generator/dropdownGroup.js for a fix

**Comment by Afredon** [comment]
I modified this part in my latest accepted push, and changed the way selectedIndex is passed to the final comboBox through an extension of datum, is that not the version you started from ?

**Comment by djmiley** [comment]
My suspicion is that `selectedIndex: sc.model.products.indexOf(sc.model.selectedProduct)` set `selectedIndex` to -1

**Comment by tlsim** [comment]
> changed the way selectedIndex is passed to the final comboBox through an extension of datum

This makes sense - selectedIndex will need to be a model property so that subsequent `render` calls render the dropdown with the correct item displayed.

**Comment by Afredon** [comment]
selectedProduct was the model property, and the code @djmiley highlighted is where the selected index was deduced from the model property, There shouldn't be a need to store the index itself.

**Comment by tlsim** [comment]
Ok great - I hadn't seen `selectedProduct`.
