### ISSUE TITLE
Main x-axis is too wide

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#347]
The x-axis should be the same width as, and align with, the plot area.

![image](https://cloud.githubusercontent.com/assets/2017615/10791118/ddc62684-7d7e-11e5-948a-6b5690da94f5.png)

**Comment by Afredon** [comment]
Work to remove foregound layers and redesigning layout a bit more is impacting the area, so I can do that as well.

**Comment by Afredon** [comment]
Limiting the axis to the correct width create a new issue: string can be truncated, for example you can see Oct 2 but not the 5
Expanding the axis to see the 5 would then make it possible for a tick to be generated there. 
To completely solve the issue, we might need some trick like expanding the axis width after calculating the ticks or have 2 parts of different widths, one for the ticks and one for the labels.
