### ISSUE TITLE
Identify Bitcoin data source limits

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#405]
+ Limitations
+ Reliability
+ How well can we handle issues?

**Comment by tlsim** [comment]
Repeatedly selecting 'Bitcoin' from the dropdown, or clicking one of the period selectors more than about once per second results in requests failing with status `429 (Too Many Requests)`.
`Error getting historic data: [object XMLHttpRequest]` is logged to the console!

**Comment by tlsim** [comment]
Switching between generated data and Bitcoin can result in websocket connection errors which are only reported in the console:
```
WebSocket connection to 'wss://ws-feed.exchange.coinbase.com/' failed: WebSocket is closed before the connection is established.

app.js:19468 Error loading data from coinbase websocket: error undefined

app.js:19468 Error loading data from coinbase websocket: close 1006
```

**Comment by jleft** [comment]
Looking at the error object when getting historic data, it seems the rate limit is 1 request/second:

```
You have exceeded your request rate of 1 r/s.
```
