### ISSUE TITLE
Zoomed in extent is unlimited

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#411]
#168 

Don't worry about limiting the zoom to a specific zoom level, just ensure the user can't zoom in so far that the chart blows up.

**Comment by djmiley** [comment]
Word of warning- we currently only have reference to relative zoom level, and not absolute zoom level. d3fc. 
Also, talked to Chris Price about re-initialisation of zoom, it seems this is unavoidable. See source code of http://d3fc.io/examples/low-barrel/index.html for details
