### ISSUE TITLE
Primary chart initially not visible when navigating to app in IE.

### ISSUE THREAD

**Issue by tlsim** [ScottLogic/d3fc-showcase#423]
IE 11
With developer tools closed, navigate to http://scottlogic.github.io/d3fc-showcase/

Expected to see the primary chart, but it is not visible:

![ieprimary](https://cloud.githubusercontent.com/assets/4527716/11335550/01ff9868-91d5-11e5-84f2-6f3fd0cd1f4d.png)

Reloading the page or resizing the window will make the primary chart appear.

**Comment by Afredon** [comment]
Similar issue but with a slight variation with Edge:
![edgeissue423](https://cloud.githubusercontent.com/assets/14907010/11335733/ebe77102-91d6-11e5-8d93-b48e612bcb27.PNG)

**Comment by tlsim** [comment]
Resolved by #435 ?

**Comment by jleft** [comment]
Looks okay to me in Edge.
