### ISSUE TITLE
Firefox: focus rectangle in the navbar missing its top border

### ISSUE THREAD

**Issue by Afredon** [ScottLogic/d3fc-showcase#424]
![firefoxnavcrop](https://cloud.githubusercontent.com/assets/14907010/11335766/33b5ae5e-91d7-11e5-9244-155de2f38462.PNG)

The rectangle seems cropped.
Looking at elements heights, these seem inconsistent: multi 67px height, background 63px, extent 61px, which could be related.

**Comment by Afredon** [comment]
Similarly, in Chrome the bottom line is missing:
![chromenavcrop](https://cloud.githubusercontent.com/assets/14907010/11336721/8fbed844-91df-11e5-9068-d9514c2a5004.PNG)

**Comment by jleft** [comment]
Thanks for raising this, but is this still relevant now that the navigator handles have been added in #388?

![handles](https://cloud.githubusercontent.com/assets/2017615/11337636/62c5fce4-91e6-11e5-992e-e24cb7aa030a.PNG)

**Comment by Afredon** [comment]
It's even less urgent than before, but the current appearence of the navigator could make us forget that there is something off here, and it'd be nice to know why.

**Comment by jleft** [comment]
Now that #428 has been merged, can this be closed?

**Comment by Afredon** [comment]
I think there won't be any focus rectangle anymore from now on, so it should be ok to cancel this issue.
To be safe, we can wait until I merged the highlight branch and see what it looks like together.

**Comment by jleft** [comment]
Ok, no problem happy to wait for #418 :)

**Comment by Afredon** [comment]
Confirmation: it's irrelevant after merging branches.
