### ISSUE TITLE
Navigator handles showing lower than expected again

### ISSUE THREAD

**Issue by rjmcneill** [ScottLogic/d3fc-showcase#438]
![nav](https://cloud.githubusercontent.com/assets/10117342/11478580/cc20e90c-9785-11e5-91ef-f5d37ca556a2.png)

**Comment by Afredon** [comment]
There's a formula calculating the circle height in the code I pushed last week, the issue should be here then. Do you have a screen shot ? I didn't see any issue with the handles when I pushed, so I'm curious to see what went wrong

**Comment by rjmcneill** [comment]
![nav](https://cloud.githubusercontent.com/assets/10117342/11478574/c2cc369a-9785-11e5-9e9c-3cc282347dbb.png)

**Comment by rjmcneill** [comment]
@Afredon there you go! :smile:

**Comment by Afredon** [comment]
What the hell is that ?? :scream:

**Comment by Afredon** [comment]
I remember in nav, I made a change that I seemed to have lost at some point, maybe during a merge:
 ``` js
  brush.on('brush', function() {
                var width = selection.select('.plot-area').select('.extent').attr('width');

                // Hide the bar if the extent has no length
                if (width > 0) {
                    brushHide = false;
                } else {
                    brushHide = true;
                }

                setHide(selection, brushHide);
```

can be replaced by 
``` js
    brush.on('brush', function() {
                setHide(selection, brush.empty());
```

That might help here

**Comment by rjmcneill** [comment]
Cheers @Afredon 
I'll have a look at testing that tomorrow

**Comment by Afredon** [comment]
Ok all my uses of brush.empty() need to be removed too. Sorry about that. The brush being forced to 2 dimensional by the multi, it returns empty at true when the y are the same, even if there is some x extent, so in our case it's wrong.

**Comment by Afredon** [comment]
That's the changeset where I broke it: https://github.com/ScottLogic/d3fc-showcase/commit/7b78f49ce57255c1ff6e226dab984126e7377cf1

**Comment by Afredon** [comment]
However, it would still be better to use brush.extent instead of the width from the DOM in the 'brush' event
