### ISSUE TITLE
No data and coinbase limit not handled

### ISSUE THREAD

**Issue by rjmcneill** [ScottLogic/d3fc-showcase#464]
![consoleerror1](https://cloud.githubusercontent.com/assets/10117342/11662691/e5797464-9dcf-11e5-98a5-b5447134f6bf.png)
![consoletrace1](https://cloud.githubusercontent.com/assets/10117342/11662693/e6b6af86-9dcf-11e5-9a7d-591582e64679.png)

From @tlsim :
This array is needed in order to update the data when a new trade arrives, now that collectOhlc does not depend on coinbaseWebsocket. I'm seeing when switching between periods (above the Coinbase rate limit) that it can become inconsistent (wrong period, empty array). The chart doesn't cope well with trying to display an empty data array - we get console errors for invalid <path> attributes.

**Comment by rjmcneill** [comment]
Why don't we just revert back to data gen if we have no data or get an error from coinbase?
We could propagate the error up to where we handle it, and print it out for the user.
It would also mean that we're still showing off the graph and stuff, rather than just printing the error out for the user.

**Comment by tlsim** [comment]
Split into the referenced issues.
