### ISSUE TITLE
Bitcoin volume format broken

### ISSUE THREAD

**Issue by jdhodges431** [ScottLogic/d3fc-showcase#486]
Seems we have wildly varying volume values:

![image](https://cloud.githubusercontent.com/assets/14218569/11901001/18909462-a5a1-11e5-969b-0db036f84e90.png)

![image](https://cloud.githubusercontent.com/assets/14218569/11901055/62b6ea6e-a5a1-11e5-9553-b7501642c789.png)

**Comment by jleft** [comment]
Good spot
