### ISSUE TITLE
Double-check the RSI output

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc-showcase#501]
The RSI look more 'noisy' than I would have expected. Can someone please double-check the chart by computing an RSI independently (Excel perhaps?)

**Comment by jdhodges431** [comment]
Here's the RSI for BCD-USD daily:
![image](https://cloud.githubusercontent.com/assets/14218569/12113258/7bddd1be-b399-11e5-9bd0-73d8dfbbefea.png)

Then here it is plotted in excel:
![image](https://cloud.githubusercontent.com/assets/14218569/12113286/a9f35f42-b399-11e5-85dc-c6d10668e6eb.png)

Definitely looks like we have an issue.

**Comment by ColinEberhardt** [comment]
Thanks - it really didn't look right to me!

We've got a copy of this book in the office 'library':

http://www.amazon.com/Technical-Analysis-Edition-Steven-Achelis/dp/0071826297

It should have a description of RSI and perhaps even test data as well.
