### ISSUE TITLE
Area series y0 value (baseline) can appear above the x-axis

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#91]
This leaves a gap, as shown below (highlighted in yellow); this gap should be removed, and the bottom of the area series should meet the x-axis.

![area-series-baseline](https://cloud.githubusercontent.com/assets/2017615/9225454/67701742-4101-11e5-9136-70f9d6fa0f93.PNG)

**Comment by djmiley** [comment]
https://github.com/ScottLogic/d3fc-showcase/commit/0bb7518ad8795394b6150f0532606e63aebb5cfa

Could it be anything to do with this?
