### ISSUE TITLE
Does the latest price on the area series and annotation align properly?

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#92]
Sometimes it appears that the latest price annotation and the latest price shown on the area series don't match:

![area-series-latest-price](https://cloud.githubusercontent.com/assets/2017615/9225502/b53e8706-4101-11e5-9fb4-1ba2b64a5995.PNG)

**Comment by djmiley** [comment]
Also on line.

**Comment by djmiley** [comment]
Resolved by #112 ?
