### ISSUE TITLE
The chart should fill the screen on mobile devices

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#95]
The chart should fill to the edge of the screen and excess white space should be removed:

![excess-whitespace](https://cloud.githubusercontent.com/assets/2017615/9225708/bc6edf5c-4102-11e5-9b81-6286aa71688f.PNG)

**Comment by djmiley** [comment]
I'll work on this.

**Comment by djmiley** [comment]
I think this can be solved at the moment by increasing the variables `maxWidthToHeightRatio` and `maxHeightToWidthRatio` from 1.5 to 16:9
