### ISSUE TITLE
The primary chart and secondary chart should share the same x-axis

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc-showcase#96]
The primary chart and secondary chart should share the same x-axis, which should appear below the secondary chart. If the secondary chart is hidden, it should still be shown below the primary chart.

Current:

![axis](https://cloud.githubusercontent.com/assets/2017615/9225901/d7491d5a-4103-11e5-84cf-d8d8814c6c4a.PNG)

Desired (rough mock-up):

![axis-2](https://cloud.githubusercontent.com/assets/2017615/9225906/deabb5bc-4103-11e5-8dfa-737a6226211a.png)

**Comment by djmiley** [comment]
I'm working on this.
